name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all branches

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # or the version you need

      - name: Build project
        run: |
          npm install
          npm run build

      - name: List files after build
        run: |
          ls -R  # List all files and directories

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the default token
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Actions"

          # Check if the gh-pages branch exists; if not, create it
          if git show-ref --verify --quiet refs/heads/gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages  # Create a new orphan branch
          fi

          git reset --hard

          # Check if the dist directory exists and copy files
          if [ -d "dist" ]; then
            cp -r dist/* .  # Copy contents of the dist directory to root
          else
            echo "Dist directory does not exist. Aborting deployment."
            exit 1  # Exit the script if the dist directory doesn't exist
          fi

          git add .
          git commit -m "Deploy updates from GitHub Actions" || echo "No changes to commit"
          git push --force origin gh-pages
