name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # or the version you need

      - name: Build project
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the default token
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Actions"

          # Check if the gh-pages branch exists, if not, create it
          if git show-ref --quiet refs/heads/gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
            git commit --allow-empty -m "Initial commit for gh-pages"
          fi

          git reset --hard

          # Check if the build directory exists and copy files
          if [ -d "build" ]; then
            cp -r build/* .  # Copy contents of the build directory to root
          else
            echo "Build directory does not exist, creating a placeholder."
            mkdir build
          fi

          git add .
          git commit -m "Deploy updates from GitHub Actions" || echo "No changes to commit"
          git push --force origin gh-pages
